import type { Metadata } from "next";
import { geistSans, geistMono } from './fonts';
import './globals.css';
import ClientLayout from './client-layout';

export const metadata: Metadata = {
  title: "Think AI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        <ClientLayout>{children}</ClientLayout>
      </body>
    </html>
  );
}
